### ISSUE TITLE
key tutanota-credentials not found

### ISSUE THREAD

**Issue by Xathros1** [flathub/com.tutanota.Tutanota#78] opened 2022-02-10 20:35 UTC
Hello,

it's not possible to login with stored login credentials.

OS: openSUSE Tumbleweed x86_64 
Kernel: 5.16.5-1-default 
DE: GNOME 41.3 

I first login normally and save the credentials, after that I close the window and open a new tutanota window, then it cannot find the saved credentials

output of `flatpak run com.tutanota.Tutanota`

> 
> [2 preload-host-spawn-strategy] Running: /app/bin/zypak-helper child - /app/lib/tutanota/tutanota-desktop --type=zygote --enable-crashpad
> the monkey has been patched
> (node:2) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
> (Use `tutanota-desktop --trace-deprecation ...` to show where the warning was created)
> version:   3.91.10
> Gtk-Message: 21:27:51.450: Failed to load module "canberra-gtk-module"
> Gtk-Message: 21:27:51.450: Failed to load module "canberra-gtk-module"
> libGL error: MESA-LOADER: failed to retrieve device information
> libGL error: MESA-LOADER: failed to open amdgpu: /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/amdgpu_dri.so: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden (search paths /usr/lib/x86_64-linux-gnu/GL/default/lib/dri, suffix _dri)
> libGL error: failed to load driver: amdgpu
> resolving key... tutanota-vault
> config up to date
> [ApplicationWindow] startFile:  file:///app/lib/tutanota/resources/app.asar/index-desktop.html
> [DownloadManager] getting dictionaries from: https://mail.tutanota.com/desktop//dictionaries/
> default mailto handler: false
> [DownloadManager] spellcheck-dictionary-initialized de
> key tutanota-vault not found, generating a new one
> libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
> [46:0210/212751.512753:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
> libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
> [120:0210/212751.535266:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
> sseInfo corrupted or not present, making sure pushEncSessionKeys and scheduled alarms are cleared
> Resetting stored state
> invalidating alarms for all windows
> invalidating alarms for window 1
> [2:0210/212751.546647:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
> [2:0210/212751.557187:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
> Webapp ready
> no update info on disk, disabling updater.
> [2:0210/212751.603429:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
> desktop file exists, checking version...
> scheduling to check sse in 1 seconds
> scheduling to check sse in 1 seconds
> scheduling to check sse in 10 seconds
> sse info not available, skip reconnect
> scheduling to check sse in 10 seconds
> sse info not available, skip reconnect
> scheduling to check sse in 10 seconds
> sse info not available, skip reconnect
> scheduling to check sse in 10 seconds
> sse info not available, skip reconnect
> [2:0210/212822.899229:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
> resolving key... tutanota-credentials
> key tutanota-credentials not found, generating a new one
> sseInfo corrupted or not present, making sure pushEncSessionKeys and scheduled alarms are cleared
> Resetting stored state
> invalidating alarms for all windows
> invalidating alarms for window 1
> storing push identifier
> scheduling to check sse in 1 seconds
> storing push identifier
> last missed notification check: { lastMissedNotificationCheckTime: null }
> scheduling to check sse in 15 seconds
> starting sse connection
> lookup sse request
> established SSE connection
> received new timeout: heartbeatTimeout:240
> scheduling to check sse in 288 seconds
> sse heartbeat 240
> scheduling to check sse in 288 seconds
> sse heartbeat 240
> scheduling to check sse in 288 seconds
> downloading missed notification
> lookup
> missed notification response 200
> dl missed notification response closed
> MissedNotification is empty
> scheduling to check sse in 288 seconds
> [2:0210/212834.416450:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
> [ApplicationWindow] startFile:  file:///app/lib/tutanota/resources/app.asar/index-desktop.html
> [DownloadManager] getting dictionaries from: https://mail.tutanota.com/desktop//dictionaries/
> [2:0210/212837.998016:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
> [2:0210/212838.000120:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
> resolving key... tutanota-credentials
> key tutanota-credentials not found, generating a new one
>

**Comment by charlag** [comment] 2022-02-11 08:02
Duplicate of #77

**Closed by charlag** 2022-02-11 08:02 UTC
